apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment 
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redislabs/redisearch:latest
        ports:
        - containerPort: 6379
